spring:
  #===============DataSource=================
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/air?characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT
    username: root
    password: 123456
#  datasource:
#    username: root
#    password: 123456
#    url: jdbc:mysql://localhost/springboot?characterEncoding=utf-8&useSSl=false
#    driver-class-name: com.mysql.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#    filters: stat,wall,log4j
#    initialSize: 5
#    minIdle: 5
#    maxActive: 20
#    maxWait: 60000
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: SELECT 1 FROM DUAL
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: false
#    maxPoolPreparedStatementPerConnectionSize: 20
#    connectionProperties:
#    druid:
#      stat:
#        mergeSql: true
#        slowSqlMillis: 5000
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.deceen.demo.entity
  configuration:
    map-underscore-to-camel-case: true

server:
  context-path: /demo
  port: 8080
  tomcat:
    uri-encoding: utf-8